using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following 
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("TimeCard")]
[assembly: AssemblyDescription("Visit the Apprenda website at http://www.apprenda.com/")]
[assembly: AssemblyConfiguration("This assembly was generated by kcamp at 10/28/2016 11:23:47.")]
[assembly: AssemblyCompany("Apprenda, Inc.")]
[assembly: AssemblyProduct("Apprenda Platform")]
[assembly: AssemblyCopyright("Copyright © Apprenda Inc. 2016")]
[assembly: AssemblyTrademark("Various trademarks held by their respective owners.")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible 
// to COM components.  If you need to access a type in this assembly from 
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("d0cc8d42-cc21-4fc0-861f-a6349b1b74f8")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Revision and Build Numbers 
// by using the '*' as shown below:
[assembly: AssemblyVersion("6.6.0")]
[assembly: AssemblyFileVersion("6.6.0.0")]
